apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wcerxjyye-python 
  janus-idp.io/tekton: wcerxjyye-python
  backstage.io/kubernetes-id: wcerxjyye-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wcerxjyye-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  